apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrtopg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shrtopg
  template:
    metadata:
      labels:
        app: shrtopg
    spec:
      containers:
      - image: okteto.dev/shrtopg:latest
        name: shrtopg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8114dec5-86dd-4fdf-a3fe-52720b967fe7"
        - name: Vless_Path
          value: "/8114dec5-86dd-4fdf-a3fe-52720b967fe7"
        - name: Vmess_UUID
          value: "5089032d-2977-4c70-874e-b290878e1085"
        - name: Vmess_Path
          value: "/5089032d-2977-4c70-874e-b290878e1085"
        - name: Share_Path
          value: "/v2link"
